---
name: Molecule Test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: "${{ github.repository }}"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with molecule
        working-directory: "${{ github.repository }}"
        run: |
          molecule test